### ISSUE TITLE
use of eeg_SASICA on matrix data instead of EEG structure

### ISSUE THREAD

**Issue by kurokirasama** [dnacombo/SASICA#11]
Hello, is it possible to use this function on a matrix input data (num channels x num data)?
I have calculated weights, sphere, compvars, bias, signs ,lrates and activations, but I want to bypass the EEGLab structure...

**Comment by dnacombo** [comment]
Hi,
Not really, no. Good luck!

Le jeu. 3 janv. 2019 à 21:39, kurokirasama <notifications@github.com> a
écrit :

**Comment by kurokirasama** [comment]
Hi, thanks for your response, I finally was able to adapt your script to be used on matrix input data, at least the algorithms i was using...
