### ISSUE TITLE
Error on waitbar when drawing figure

### ISSUE THREAD

**Issue by ritcheym** [dnacombo/SASICA#2]
I received the following set of error messages after calling eeg_SASICA:

> Drawing figure...
More than 64 electrodes: electrode locations not shown
Error using getappdata
Value must be a handle.

> Error in waitbar>extractHandles (line 285)
handles = getappdata(fighandle,'TMWWaitbar_handles');

> Error in waitbar (line 88)
            handles = extractHandles(whichbar);

> Error in eeg_SASICA>pop_selectcomps (line 1330)
    waitbar(ri/comptot,findobj('tag','waitcomp'))

> Error in eeg_SASICA (line 85)
    eval(cfg);

> Error in eeg_SASICA (line 651)
            eeg_SASICA(EEG,['pop_selectcomps(EEG, [' num2str(cmps) '],' num2str(ncomp) ');']);

Commenting out the call to waitbar (eeg_SASICA line 1330) works as a temporary solution. 
Matlab version R2013a, EEGLAB version 13.4.4b

**Comment by dnacombo** [comment]
Thanks for this report. Will fix this asap.

**Comment by dnacombo** [comment]
Just pushed new version. Please let me know if still problems.
