### ISSUE TITLE
Function initialize failure

### ISSUE THREAD

**Issue by Aleirran** [dnacombo/SASICA#4]
Not sure, if the cause in SASICA itself or what - when I press "Compute" Matlab fails with bugreport "Undefined function 'xcorr' for input arguments of type 'single'."
If I open and run xcorr.m manually, Matlab adds it to path and proceeds, but fails on something else, like 'optimset'.

**Comment by dnacombo** [comment]
Thanks for your feed back. Can you send the full error message?
Thanks

**Comment by Aleirran** [comment]
Well, I'm asch.raureif, so you already received that report. Sorry for doubling.
