### ISSUE TITLE
Reference to non-existent field 'blinkchanname'.

### ISSUE THREAD

**Issue by Aleirran** [dnacombo/SASICA#5]
When I try to use SASICA, it's window blinks for a second, then disappears, instead giving this bugreport in matlab:
Reference to non-existent field 'blinkchanname'.

Error in SASICA>SASICA_OpeningFcn (line 192)
            chname = channamecheck(cfg.(f{i_f}{1}).(f{i_f}{2}),hObject);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

**Comment by dnacombo** [comment]
I know this bug. Will fix it asap. Please enter
SASICA resetprefs
In the command window.

**Comment by Aleirran** [comment]
Could you also add in readme requirements to Matlab/eeglab version?
I use R2014a, and, I guess, it's already outdated a bit.

**Comment by Aleirran** [comment]
Another... something.

ERROR. Please send the entire error message below to max.chaumon@gmail.com. Thanks for your help!
================================
This is SASICA_1.3
This is MATLAB 8.6.0.267246 (R2015b)
Running on PCWIN64
================================
================================
ERROR. Please send the entire error log below to max.chaumon@gmail.com. Thanks for your help!
================================
This is SASICA_1.3
This is MATLAB 8.6.0.267246 (R2015b)
Running on PCWIN64
MARA:
  enable: 0
FASTER:
  enable: 0
  blinkchans: 
ADJUST:
  enable: 1
chancorr:
  enable: 0
  channames: 
  corthresh: auto 4
EOGcorr:
  enable: 1
  Heogchannames: 31
  corthreshH: auto 4
  Veogchannames: 1
  corthreshV: auto 4
resvar:
  enable: 0
  thresh: 15
SNR:
  enable: 0
  snrcut: 1
  snrBL: -Inf    0
  snrPOI: 0  Inf
trialfoc:
  enable: 1
  focaltrialout: auto
focalcomp:
  enable: 1
  focalICAout: auto
autocorr:
  enable: 1
  autocorrint: 20
  dropautocorr: auto
opts:
  noplot: 0
  nocompute: 0
  FontSize: 14
Undefined function or variable 'DEFAULT_COLORMAP'.

Error in topoplot (line 590)
    cmap = colormap(DEFAULT_COLORMAP);

Error in pop_selectcomps (line 155)
            topoplot( EEG.icawinv(:,ri), EEG.chanlocs, 'verbose', ...

Error in eeg_SASICA (line 89)
        eval(cfg);

Error in eeg_SASICA (line 732)
            eeg_SASICA(EEG,['pop_selectcomps(EEG, [' num2str(cmps) '],' num2str(ncomp) ');']);

Error in SASICA>push_ok_Callback (line 616)
    [EEG, cfg] = eeg_SASICA(EEG,cfg);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SASICA('push_ok_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback


When it tried to plot topos.

**Comment by dnacombo** [comment]
This looks like a problem with your eeglab. Have you tried updating to the latest version?

**Comment by Aleirran** [comment]
That was exactly latest version.
Oddly, returning to previous version fixed this.

**Comment by zhang470** [comment]
I am using SASICA 1.3.3. The error can be fixed by making a minor change in Line 668  of eeg_SASICA.m       
Original Line 668: blinkchanname = chnb(blinkchanname);
Fixed Line:        blinkchanname = chnb(blinkchans);
This is due to the fact that the cfg struct has the actual field name "blinkchans" under cfg.FASTER instead of "blinkchanname" even though conceptually they are meant to be the same.

**Comment by dnacombo** [comment]
Thanks for the note. I'll have this fixed in the next release. Not before
next week, though. Thanks again.
zhang470 <notifications@github.com> schrieb am So., 5. Feb. 2017 um 13:04:
