### ISSUE TITLE
Cannot enter EOG channels

### ISSUE THREAD

**Issue by Aleirran** [dnacombo/SASICA#6]
SASICA 1.3.4/ Egglab 14
I enter corresponding labels "Veog/Heog" or numbers (tried both) into proper fields, but hitting "Compute" resets fields and it says "No EOG channels".

Also, some of my data causes this bugreport:
Error using pop_selectcomps (line 126)
don't panic

Error in eeg_SASICA (line 89)
        eval(cfg);

Error in eeg_SASICA (line 736)
            eeg_SASICA(EEG,['pop_selectcomps(EEG, [' num2str(cmps) '],' num2str(ncomp) ');']);

Error in SASICA>push_ok_Callback (line 594)
    [EEG, cfg] = eeg_SASICA(EEG,cfg);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SASICA('push_ok_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback

What should I check them for?

**Comment by dnacombo** [comment]
Would you mind uploading your datasets [here](https://www.dropbox.com/request/f4p0goNpWoWBSUjVTfgd) so I can test it myself?
Thanks
