### ISSUE TITLE
SASICA input error

### ISSUE THREAD

**Issue by jcmizelle** [dnacombo/SASICA#7]
Hi, Max. Running into some trouble with SASICA. MATLAB 2016b and 2013b - both show the same problem. System is Windows 7, 64 bit OS. I can run SASICA once just fine, but then things go a bit crazy. SASICA window will open off of the top of the MATLAB screen. It will not contain any of the defaults. The SASICA window will then jump down into the usable portion of the screen and throw the error below. If I then ask SASICA to 'compute', the bottom error message is displayed.

I'd appreciate any advice you can offer!

Best,
Chris

Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg)) ');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating Menu Callback

================================
================================
ERROR. Please send the entire error log below to max.chaumon@gmail.com. Thanks for your help!
================================
This is SASICA_1.3.4
This is MATLAB 9.1.0.441655 (R2016b)
Running on PCWIN64
MARA:
  enable: 1
FASTER:
  enable: 1
  blinkchanname: VEO
ADJUST:
  enable: 1
chancorr:
  enable: 1
  channames: No channel
  corthresh: auto 4
EOGcorr:
  enable: 1
  Heogchannames: HEO
  corthreshH: auto 4
  Veogchannames: VEO
  corthreshV: auto 4
resvar:
  enable: 1
  thresh: 15
SNR:
  enable: 1
  snrcut: 1
  snrBL: -Inf    0
  snrPOI: 0  Inf
trialfoc:
  enable: 1
  focaltrialout: auto 2
focalcomp:
  enable: 1
  focalICAout: auto 2
autocorr:
  enable: 1
  autocorrint: 20
  dropautocorr: auto 2
opts:
  noplot: 0
  nocompute: 0
  FontSize: 14
setname: CNT file resampled
filename: test.set
filepath: C:\data\eeg\preproc\test_data
subject: 
group: 
condition: 
session: 
comments: Original file: Z:\storage\Data\Alex Tool Use\Y_S001.cnt
nbchan: 66
trials: 1
pnts: 623375
srate: 250
xmin: 0
xmax: 2493.496

**Comment by dnacombo** [comment]
Thanks Chris, for your report. Could you please upload your dataset [here](https://www.dropbox.com/request/f4p0goNpWoWBSUjVTfgd)? 
Thanks!

**Comment by jcmizelle** [comment]
Thanks for such a quick reply! Files are uploading now. The issues seem to
have started after I used Ctrl + C to break the process to change an input.
After this, calling SASICA either from the command line or through the
EEGLAB GUI resulted in the reported errors.

Thanks again!
Chris

**Comment by dnacombo** [comment]
Hi,
In that case, I recommend running 
`SASICA resetprefs`
and trying again. Your Ctrl + C probably happened at a wrong moment (bad luck!).
Let me know how it works.

**Comment by jcmizelle** [comment]
Hi, Max. No luck. SASICA resetprefs at the command line (even after
restarting the computer) returns the following:

Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg))
');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
varargin{:});

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

Thanks,
Chris

**Comment by jcmizelle** [comment]
Even trying to run SASICA from the command line (using the following)
returns the error below. The EEG variable passed into eeg_SASICA is
definitely a 1x1 structure with ICA weights.

    EEG_ICA = eeg_SASICA(EEG,'MARA_enable',0,...
        'FASTER_enable',1,...
        'FASTER_blinkchanname','VEO',...
        'ADJUST_enable',1,...
        'chancorr_enable',0,...
        'chancorr_channames','No channel',...
        'chancorr_corthresh','auto 4',...
        'EOGcorr_enable',0,...
        'EOGcorr_Heogchannames','HEO',...
        'EOGcorr_corthreshH','auto 4',...
        'EOGcorr_Veogchannames','VEO',...
        'EOGcorr_corthreshV','auto 4',...
        'resvar_enable',0,...
        'resvar_thresh',15,...
        'SNR_enable',0,...
        'SNR_snrcut',1,...
        'SNR_snrBL',[-Inf 0] ,...
        'SNR_snrPOI',[0 Inf] ,...
        'trialfoc_enable',0,...
        'trialfoc_focaltrialout','auto',...
        'focalcomp_enable',1,...
        'focalcomp_focalICAout','auto',...
        'autocorr_enable',1,...
        'autocorr_autocorrint',20,...
        'autocorr_dropautocorr','auto',...
        'opts_noplot',1,...
        'opts_nocompute',0,...
        'opts_FontSize',14);

Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg))
');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
varargin{:});

Error in SASICA (line 106)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in eeg_SASICA (line 108)
def = SASICA('getdefs');

**Comment by dnacombo** [comment]
Hi Chris,
I'm looking into it and can't reproduce the error...
Can you download SASICA from this location again and tell me how it works?
https://github.com/dnacombo/SASICA/archive/master.zip

you should replace the content of
/.../eeglab/plugins/SASICA
with the content of the zip file.

Sorry for the inconvenience. Let me know if you need more guidance.

When this is done, start with
EEG = pop_loadset('yourdataset.set');
then
SASICA resetprefs

Select the methods you want to use and press Compute.

Best,
Max




Le lun. 17 juil. 2017 à 18:20, jcmizelle <notifications@github.com> a
écrit :

**Comment by jcmizelle** [comment]
Hi, Max. No luck still - even SASICA resetprefs generates the error below.
I'm going to reinstall Matlab and see if that does anything - will let you
know.

Chris

Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg))
');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
varargin{:});

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

**Comment by dnacombo** [comment]
I'm clueless. My recommendatoin would be to comment out lines 170-174 in
SASICA.m
These lines are not essential anyways.

Let me know,
Max

Le mer. 19 juil. 2017 à 20:58, jcmizelle <notifications@github.com> a
écrit :

**Comment by jcmizelle** [comment]
Commenting 170-174 resulted in the GUI (called through eeglab\tools) fields
being populated with the default settings, and then returning the following
error - something different at least.

Reference to non-existent field 'com'.

Error in SASICA>SASICA_OutputFcn (line 227)
    varargout{2} = handles.com;

Error in gui_mainfcn (line 217)
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

Error while evaluating Menu Callback


The above error is also generated from the command line call to SASICA
below:


    EEG_ICA = eeg_SASICA(EEG,'MARA_enable',0,...
        'FASTER_enable',1,...
        'FASTER_blinkchanname','VEO',...
        'ADJUST_enable',1,...
        'chancorr_enable',0,...
        'chancorr_channames','No channel',...
        'chancorr_corthresh','auto 4',...
        'EOGcorr_enable',0,...
        'EOGcorr_Heogchannames','HEO',...
        'EOGcorr_corthreshH','auto 4',...
        'EOGcorr_Veogchannames','VEO',...
        'EOGcorr_corthreshV','auto 4',...
        'resvar_enable',0,...
        'resvar_thresh',15,...
        'SNR_enable',0,...
        'SNR_snrcut',1,...
        'SNR_snrBL',[-Inf 0] ,...
        'SNR_snrPOI',[0 Inf] ,...
        'trialfoc_enable',0,...
        'trialfoc_focaltrialout','auto',...
        'focalcomp_enable',1,...
        'focalcomp_focalICAout','auto',...
        'autocorr_enable',1,...
        'autocorr_autocorrint',20,...
        'autocorr_dropautocorr','auto',...
        'opts_noplot',1,...
        'opts_nocompute',0,...
        'opts_FontSize',14);

**Comment by dnacombo** [comment]
Ah... you can comment that line 227 as well...

**Comment by jcmizelle** [comment]
Sorry for my delayed response. Sat back down to work more with SASICA
today, and your most recent suggestion took care of the issue - both from
the command line and from the GUI.

The only other minor thing is that there are no plots generated (throws an
error; sorry, I'm not in the office now and I don't remember it exactly).
Not a big deal - I can always plot components manually from eeglab code.

Thanks again for your responsiveness and help in working through all of
this!
Chris

**Comment by sebsau** [comment]
Dear Max,

I've got the same problem when using SASICA in EEGLAB.

```
Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg)) ');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});


Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating Menu Callback.
```

This happens both with MATLAB 2017a and 2018a, and I am pretty sure that the input is a valid EEG struct. Do you have any new insights into what might cause this error?

Thanks a lot for this great tool, in any case!

**Comment by dnacombo** [comment]
Hi Sebastian,
Thanks for your comment.
Does typing `SASICA resetprefs` in the command window solve the issue?

**Comment by sebsau** [comment]
Sorry, for not mentioning this. I tried `SASICA resetprefs` but it unfortunately doesn't solve the problem.

**Comment by dnacombo** [comment]
But it did work before, right?

**Comment by sebsau** [comment]
Yes, I have used SASICA without problems before. But then suddenly this error message occurs every time I call it. (I can't remember whether there was a SASICA update that I installed through the EEGLAB GUI, though. Maybe that caused the error?)

**Comment by dnacombo** [comment]
I haven't made any update recently...
What does it say if you comment lines 758 759 760?

**Comment by sebsau** [comment]
When I run it through the command line like this

```
[EEG] = SASICA(EEG,'MARA_enable',0,'FASTER_enable',0,'FASTER_blinkchanname','No channel','ADJUST_enable',1,'chancorr_enable',1,'chancorr_channames','E14 E21 E25 E127 E128','chancorr_corthresh','auto 4','EOGcorr_enable',1,'EOGcorr_Heogchannames','E125','EOGcorr_corthreshH','auto 4','EOGcorr_Veogchannames','E8','EOGcorr_corthreshV','auto 4','resvar_enable',0,'resvar_thresh',15,'SNR_enable',0,'SNR_snrcut',1,'SNR_snrBL',[-Inf 0] ,'SNR_snrPOI',[0 Inf] ,'trialfoc_enable',1,'trialfoc_focaltrialout','auto','focalcomp_enable',1,'focalcomp_focalICAout','auto','autocorr_enable',1,'autocorr_autocorrint',20,'autocorr_dropautocorr','auto','opts_noplot',1,'opts_nocompute',0,'opts_FontSize',14)
```

I also get the error message: 

```
Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg)) ');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});


Error in SASICA (line 106)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in eeg_SASICA (line 108)
def = SASICA('getdefs');

Error in SASICA>SASICA_OpeningFcn (line 162)
    EEG = eeg_SASICA(EEG,cfg);

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});

Error in SASICA (line 106)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
```

I also tried the following: Open SASICA in the GUI and then clicking on "Options > Reset default values". Then I entered my specifications (see above), but when I click on "Compute", all the fields gray out and take the default values again. SASICA nevertheless runs and prints the topoplots with selecting components according to what I specified. But when I click on "ok" in the topoplots and then go to "Remove components" in the GUI, no component is pasted there and MATLAB throws this error:

```
Error using SASICA>struct2vararg (line 759)
input should be 1x1 structure array

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>push_ok_Callback (line 608)
com = ['[EEG] = SASICA(EEG,' vararg2str(struct2vararg(cfg)) ');'];

Error in gui_mainfcn (line 75)
        feval(varargin{:});


Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SASICA('push_ok_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```

Could it have anything to do with any settings on my computer?

**Comment by sebsau** [comment]
Hi Max,

unfortunately, I don't fully get what you mean by `[[nothing here = ]]`.

I tried to use `[EEG] = eeg_SASICA(EEG,'MARA_enable',0,'FASTER_enable',0,'FASTER_blinkchanname','No channel','ADJUST_enable',1,'chancorr_enable',1,'chancorr_channames','E14 E21 E25 E127 E128','chancorr_corthresh','auto 4','EOGcorr_enable',1,'EOGcorr_Heogchannames','E125','EOGcorr_corthreshH','auto 4','EOGcorr_Veogchannames','E8','EOGcorr_corthreshV','auto 4','resvar_enable',0,'resvar_thresh',15,'SNR_enable',0,'SNR_snrcut',1,'SNR_snrBL',[-Inf 0] ,'SNR_snrPOI',[0 Inf] ,'trialfoc_enable',1,'trialfoc_focaltrialout','auto','focalcomp_enable',1,'focalcomp_focalICAout','auto','autocorr_enable',1,'autocorr_autocorrint',20,'autocorr_dropautocorr','auto','opts_noplot',1,'opts_nocompute',0,'opts_FontSize',14);`

But that leads to another error:

```
Error using isstruct
Too many input arguments.

Error in SASICA>struct2vararg (line 765)
    if isstruct(s.(fn{i_f}));

Error in SASICA>struct2vararg (line 769)
            v = [v struct2vararg(s.(fn{i_f}),[fn{i_f}])];

Error in SASICA>SASICA_OpeningFcn (line 171)
    handles.com = ['[EEG] = SASICA([],' vararg2str(struct2vararg(cfg)) ');'];

Error in gui_mainfcn (line 177)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});


Error in SASICA (line 106)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in eeg_SASICA (line 108)
def = SASICA('getdefs');
```

(I'm sorry, this is probably a rookie mistake, but I'm quite new to Matlab.) What I am ultimately after is that I get the components to be rejected into the Tools > Reject components window.

**Comment by dnacombo** [comment]
By [nothing here] I meant to just not provide any output to your SASICA line. Just type 
`SASICA(EEG, 'MARA_enable',0,'FASTER_enable',0,'FASTER_blinkchanname','No channel','ADJUST_enable',1 `...

what happens if you type
`cfg = SASICA('getdefs')`

Can you upload your data here?
https://www.dropbox.com/request/f4p0goNpWoWBSUjVTfgd

**Comment by dnacombo** [comment]
I'm clueless. It works fine on my computer... MATLAB 2017b 
Just updated eeglab to the latest...
Can you comment lines 170-174 and 227
(and by the way, uncomment lines 758-760)
and let me know what happens.
Thanks

**Comment by sebsau** [comment]
I am running Matlab on a Mac and also tried it on a Windows machine, with the same error messages. :(

Now I commented 170-174 and 227 (and uncommented 758-760). Then I get a new error message:

`================================
================================
ERROR. Please send the entire error log below to max.chaumon@gmail.com. Thanks for your help!
================================
This is SASICA_1.3.4
This is MATLAB 9.2.0.556344 (R2017a)
Running on MACI64
MARA:
  enable: 0
FASTER:
  enable: 0
  blinkchanname: No channel
ADJUST:
  enable: 1
chancorr:
  enable: 1
  channames: E14 E21 E25 E126 E127 E128
  corthresh: auto 4
EOGcorr:
  enable: 1
  Heogchannames: E125
  corthreshH: auto 4
  Veogchannames: E8
  corthreshV: auto 4
resvar:
  enable: 0
  thresh: 15
SNR:
  enable: 0
  snrcut: 1
  snrBL: -Inf    0
  snrPOI: 0  Inf
trialfoc:
  enable: 1
  focaltrialout: auto
focalcomp:
  enable: 1
  focalICAout: auto
autocorr:
  enable: 1
  autocorrint: 20
  dropautocorr: auto
opts:
  noplot: 0
  nocompute: 0
  FontSize: 14

Error using horzcat
Dimensions of matrices being concatenated are not consistent.

Error in SASICA>dispstruct (line 623)
            disp([repmat('  ',space), f{i_f} ': ', S.(f{i_f})])

Error in SASICA>push_ok_Callback (line 603)
    dispstruct(cfg)

Error in gui_mainfcn (line 75)
        feval(varargin{:});


Error in SASICA (line 108)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SASICA('push_ok_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.`

But when opening SASICA in the GUI, it already fills in the specs I used before (which was not the case earlier). Since it runs smoothly on your computer, maybe it is some problem with how I set up things.

**Comment by sebsau** [comment]
Big thanks for all the troubleshooting help here!

**Comment by dnacombo** [comment]
sorry I can't help more...
