### ISSUE TITLE
Negative discriminant

### ISSUE THREAD

**Issue by jessicaloke** [dnacombo/SASICA#9]
Hello, I have a set of data which is potentially very noisy. While running the ADJUST function, the script stopped with this error:

Negative Discriminant!
Output argument "last" (and maybe others) not assigned during call to "EM".

Error in ADJUST (line 310)
[soglia_V,med1_V,med2_V]=EM(nuovaV);

What does it mean?

**Comment by dnacombo** [comment]
Hi,
I have no idea. This is ADJUST code.
You will have to clear that with the ADJUST developers.

**Comment by jessicaloke** [comment]
Oh, sorry, I made a mistake posting. Thanks for the response!
